### ISSUE TITLE
Destroy causing error

### ISSUE THREAD

**Issue by DBZFYAM** [josex2r/jQuery-SlotMachine#60]
When I destroy a slotmachine with the destroy() function, I get an error that this.$tiles.unwrap() doesn't exist and the slotmachine isn't usable anymore. When removing this line, it seems to destroy just fine and functions seem to still be working. Is this a bug or unfinished feature?

**Comment by richardblondet** [comment]
Hey @DBZFYAM,  Unwrap is a jQuery function:

**[.unwrap()](https://api.jquery.com/unwrap/)**
> Remove the parents of the set of matched elements from the DOM, leaving the matched elements in their place.

I encounter this error as well while using it without jQuery. Upon checking the code https://github.com/josex2r/jQuery-SlotMachine/blob/d8c38faa31859464d6a1e700e2ff7d570e5f3392/dist/slotmachine.js#L353 the destroy method does not appear to be jQuery-free friendly.  Since the library offers a way to use without jQuery, it can be safe to assume that this is a bug.

@josex2r when do you think possible to fix this issue? I might help but I'm limited in time. 

Thanks for the amazing work!

**Comment by h0jeZvgoxFepBQ2C** [comment]
I think this is just a typo, the $ sign is just a variable name, which is not defined - probably it should be ```this.tiles.unwrap();``` without the $.. Am I right? Got bugged by this too right now

Ping @josex2r

**Comment by oldmankit** [comment]
This affects me too.

I also would like to ask for help. Can anyone show me a quick example for how to only allow one instance of a machine?

I have a function `makeWordMachine` which can be called multiple times. If there is an existing machine, it needs to be destroyed before creating a new one.

``` js
const makeWordMachine = function() {
  if (wordMachine) {
    destroy(wordMachine);
  }
  const wordMachine = new SlotMachine(el);
}
```

But this gives an error:

`Cannot access 'wordMachine' before initialization`.

I think there must be an easy way to do this, but all I can think of is creating a global variable with machineCount, which is incremented on creating a machine, which then allows me to destroy the existing machine, reset the counter to zero, and then create a new one. But that seems sloppy. I've tried a bunch of other things to get around this but so far have failed.

**Comment by royanon** [comment]
remark line 253 of slotmachine.js
// this.$tiles.unwrap();
Then it work.

**Comment by josex2r** [comment]
Sorry for my late response, I've been focused in other projects.
The changes seems to fix the problem, I'll publish a patch in a few minutes.

Thanks for contributing :)
